### ISSUE TITLE
a bug in jpl_omega function

### ISSUE THREAD

**Issue by mhyoosefian** [Edwinem/msckf_tutorial#1]
Hi. Thanks for the contribution!

It seems there is a typo in the "jpl_omega" function. in the "jpl_quat_ops.py" file, line 152, I think it should be like this:
`mat[3, 0:3] = -vec.T`

**Comment by Edwinem** [comment]
Not a typo, because numpy doesn't care if it is a row or a column vector.

`mat[3, 0:3] = -vec.T` is the same as `mat[3, 0:3] = -vec`
