### ISSUE TITLE
No modules named pyVIOSIM

### ISSUE THREAD

**Issue by WeilongXia** [Edwinem/msckf_tutorial#3]
Hi~ When I run the run_on_vi_simulator.py, it occurs that "no modules named 'pyVIOSIM' ", what can I do to solve this? Any help appreciates.

**Comment by Edwinem** [comment]
Thanks for noticing. That is a leftover script from testing an internal project. You really should only run the [run_on_euroc.py](https://github.com/Edwinem/msckf_tutorial/blob/main/examples/run_on_euroc.py) file.
